apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm
  labels:
    app.kubernetes.io/name: crm
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_EnableDiagnostics: "0"
  WEB_API_PUBLIC_PATH: "/api"
  NGINX_ENTRYPOINT_QUIET_LOGS: "1"
