apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
  namespace: crm
  labels:
    app.kubernetes.io/name: crm
type: Opaque
stringData:
  ConnectionStrings__CrmDb: "Host=postgresql.example.mdb.yandexcloud.net;Port=6432;Database=crm;Username=crm_user;Password=replace-me;SSL Mode=Require;"
